name       : haskell-hxt
version    : 9.3.1.18
release    : 3
source     :
    - https://hackage.haskell.org/package/hxt-9.3.1.18/hxt-9.3.1.18.tar.gz : 721809d89bbcaf29b2bbe3b9cdbb54e6d6a30afe7509186061898f7e8b996620
license    : MIT
component  : programming.haskell
summary    : The Haskell XML Toolbox bases on the ideas of HaXml and HXML, but introduces a more general approach for processing XML with Haskell.
description: |
    The Haskell XML Toolbox bases on the ideas of HaXml and HXML, but introduces a more general approach for processing XML with Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-hxt-regex-xmlschema-devel
    - haskell-hxt-unicode-devel
    - haskell-network-uri-devel
rundeps    :
    - devel:
        - haskell-hxt-regex-xmlschema-devel
        - haskell-hxt-unicode-devel
        - haskell-network-uri-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
