name       : haskell-hxt
version    : 9.3.1.16
release    : 2
source     :
    - https://hackage.haskell.org/package/hxt-9.3.1.16/hxt-9.3.1.16.tar.gz : 0d55e35cc718891d0987b7c8e6c43499efa727c68bc92e88e8b99461dff403e3
license    : MIT
component  : programming.haskell
summary    : The Haskell XML Toolbox bases on the ideas of HaXml and HXML, but introduces
    a more general approach for processing XML with Haskell.
description: |
    The Haskell XML Toolbox bases on the ideas of HaXml and HXML, but introduces a more general approach for processing XML with Haskell.
builddeps  :
    - haskell-cabal-install
    - haskell-hxt-regex-xmlschema
    - haskell-hxt-unicode
    - haskell-network-uri
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
